### ISSUE TITLE
It would be convenient if joindin.js could embed a grid or list timetable

### ISSUE THREAD

**Issue by JonTheNiceGuy** [joindin/JoindIn.js#16]
I would like to replace oggcamp.github.io/schedule's table based grid with a pull from the event at joind.in.

While I could simulate this with each talk represented as it's own div and supplement that with the line-item for the talk... it would be *much* easier to just pull the whole event via joindin.js :)

Happy to discuss!

**Comment by AurelioDeRosa** [comment]
I'm almost embarassed to reply now only, but I think I'll close this issue for now. I'm not very active on this lib anymore and I'd keep its footprint at a minimum.
